server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      google:
        client-id: your-app-client-id
        client-secret: your-app-client-secret
        redirect-uri: http://localhost:8080/oauth2/authorize/code/google
      github:
        client-id: your-app-client-id
        client-secret: your-app-client-secret
        redirect-uri: http://localhost:8080/oauth2/authorize/code/github
      facebook:
        client-id: your-app-client-id
        client-secret: your-app-client-secret
        redirect-uri: http://localhost:8080/oauth2/authorize/code/facebook
      okta:
        client-id: your-app-client-id
        client-secret: your-app-client-secret
        redirect-uri: http://localhost:8080/oauth2/authorize/code/okta
        authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
        token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
        user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
