site:
  title: Spring Security
  start_page: security::overview.adoc
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: ../../rwinch/antora-ui-spring/build/ui-bundle.zip
    snapshot: true
