= Preface

// FIXME: Add links for authentication, authorization, common attacks
Spring Security is a framework that provides authentication, authorization, and protection against common attacks.
// FIXME: Add links for imperative and reactive applications
Working in both imperative and reactive applications, it is the de-facto standard for securing Spring-based applications.

== Getting Started

The best way to get started is trying Hello Spring Security.

== Getting Spring Security

=== Usage with Maven

=== Usage with Gradle


[[community]]
== Spring Security Community


[[community-issues]]
=== Issue Tracking
Spring Security uses https://github.com/spring-projects/spring-security/issues[GitHub issues] to manage bug reports and enhancement requests.
Do not log it on the support forum, mailing list or by emailing the project's developers.
Such approaches are ad-hoc and we prefer to manage bugs using a more formal process.

If possible, in your issue report please provide a JUnit test that demonstrates any incorrect behaviour.
Or, better yet, provide a https://github.com/spring-projects/spring-security/pulls[pull request] that corrects the issue.
Similarly, enhancements are welcome to be logged in the issue tracker, although we only accept enhancement requests if you include corresponding unit tests.
This is necessary to ensure project test coverage is adequately maintained.

You can access the issue tracker at https://github.com/spring-projects/spring-security/issues.


[[community-becoming-involved]]
=== Becoming Involved
We welcome your involvement in the Spring Security project.
There are many ways of contributing, including reading the forum and responding to questions from other people, writing new code, improving existing code, assisting with documentation, developing samples or tutorials, or simply making suggestions.


[[community-help]]
=== Getting Help
Questions and comments on Spring Security are welcome.
You can use the Spring at Stack Overflow web site at http://spring.io/questions[http://spring.io/questions] to discuss Spring Security with other users of the framework.
Remember to use GitHub for bug reports, as explained above.

[[community-source]]
=== Source Code

Spring Security's source code can be found on GitHub at https://github.com/spring-projects/spring-security/

[[community-license]]
=== Apache 2 License

Spring Security is Open Source software released under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].

=== Social Media

include::{partialsdir}/preface/index.adoc[]

include::{include-dir}/architecture/index.adoc[]

include::{include-dir}/test/index.adoc[]

include::{include-dir}/web/index.adoc[]

include::{include-dir}/authorization/index.adoc[]

include::{include-dir}/additional-topics/index.adoc[]

include::{include-dir}/data/index.adoc[]

include::{include-dir}/appendix/index.adoc[]


