[[servlet-authentication-architecture]]
= Servlet Authentication Architecture
:figures: servlet/authentication/architecture

This discussion expands on xref:servlet/architecture.adoc#servlet-architecture[Servlet Security: The Big Picture] to describe the main architectural components of Spring Security's used in Servlet authentication.
If you need concrete flows that explain how these pieces fit together, look at the xref:servlet/authentication/index.adoc#servlet-authentication-mechanisms[Authentication Mechanism] specific sections.

* <<servlet-authentication-securitycontextholder>> - The `SecurityContextHolder` is where Spring Security stores the details of who is xref:features/authentication/index.adoc#authentication[authenticated].
* <<servlet-authentication-securitycontext>> - is obtained from the `SecurityContextHolder` and contains the `Authentication` of the currently authenticated user.
* <<servlet-authentication-authentication>> - Can be the input to `AuthenticationManager` to provide the credentials a user has provided to authenticate or the current user from the `SecurityContext`.
* <<servlet-authentication-granted-authority>> - An authority that is granted to the principal on the `Authentication` (i.e. roles, scopes, etc.)
* <<servlet-authentication-authenticationmanager>> -  the API that defines how Spring Security's Filters perform  xref:features/authentication/index.adoc#authentication[authentication].
* <<servlet-authentication-providermanager>> -  the most common implementation of `AuthenticationManager`.
* <<servlet-authentication-authenticationprovider>> - used by `ProviderManager` to perform a specific type of authentication.
* <<servlet-authentication-authenticationentrypoint>> - used for requesting credentials from a client (i.e. redirecting to a log in page, sending a `WWW-Authenticate` response, etc.)
* <<servlet-authentication-abstractprocessingfilter>> - a base `Filter` used for authentication.
This also gives a good idea of the high level flow of authentication and how pieces work together.

include::security-context-holder.adoc[leveloffset=+1]

include::security-context.adoc[leveloffset=+1]

include::authentication.adoc[leveloffset=+1]

include::granted-authority.adoc[leveloffset=+1]

include::authentication-manager.adoc[leveloffset=+1]

include::provider-manager.adoc[leveloffset=+1]

include::authentication-provider.adoc[leveloffset=+1]

include::authentication-entry-point.adoc[leveloffset=+1]

// FIXME: authenticationsuccesshandler
// FIXME: authenticationfailurehandler

include::abstract-authentication-processing-filter.adoc[leveloffset=+1]
