name: reference

on:
  push:
    branches-ignore:
      - 'gh-pages'

env:
  GH_TOKEN_DISPATCH: ${{ secrets.GH_TOKEN_DISPATCH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Dispatch Build Request
        run: ${GITHUB_WORKSPACE}/.github/actions/dispatch.sh 'rwinch/spring-reference' "$GH_TOKEN_DISPATCH"